/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.net.URL;
import javax.swing.ImageIcon;

/**
 *
 * @author iband
 */
public class FrMenu extends javax.swing.JFrame {

  /**
   * Creates new form FrMenu
   */
  public FrMenu() {
    initComponents();
    
    //Abre a tela centralizada
    this.setLocationRelativeTo(null);
  }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    jPanel1 = new javax.swing.JPanel();
    lblImagem = new javax.swing.JLabel();
    edtPkusuario = new javax.swing.JTextField();
    jLabel1 = new javax.swing.JLabel();
    btnAlterar = new javax.swing.JButton();
    barMenu = new javax.swing.JMenuBar();
    meCadastro = new javax.swing.JMenu();
    miCadUsuario = new javax.swing.JMenuItem();
    jMenuItem2 = new javax.swing.JMenuItem();
    miSair = new javax.swing.JMenuItem();
    meConsulta = new javax.swing.JMenu();
    miConUsuario = new javax.swing.JMenuItem();
    jMenuItem3 = new javax.swing.JMenuItem();
    meSobre = new javax.swing.JMenu();

    setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
    setTitle("Menu");
    addWindowListener(new java.awt.event.WindowAdapter() {
      public void windowOpened(java.awt.event.WindowEvent evt) {
        formWindowOpened(evt);
      }
    });

    jPanel1.setBackground(new java.awt.Color(102, 255, 102));

    lblImagem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/logo.png"))); // NOI18N

    edtPkusuario.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        edtPkusuarioActionPerformed(evt);
      }
    });

    jLabel1.setText("código usuário");

    btnAlterar.setText("alterar");
    btnAlterar.addMouseListener(new java.awt.event.MouseAdapter() {
      public void mouseClicked(java.awt.event.MouseEvent evt) {
        btnAlterarMouseClicked(evt);
      }
    });

    javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
    jPanel1.setLayout(jPanel1Layout);
    jPanel1Layout.setHorizontalGroup(
      jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(jPanel1Layout.createSequentialGroup()
        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addGroup(jPanel1Layout.createSequentialGroup()
            .addGap(150, 150, 150)
            .addComponent(lblImagem))
          .addGroup(jPanel1Layout.createSequentialGroup()
            .addGap(52, 52, 52)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
              .addComponent(jLabel1)
              .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(edtPkusuario, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnAlterar)))))
        .addContainerGap(132, Short.MAX_VALUE))
    );
    jPanel1Layout.setVerticalGroup(
      jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(jPanel1Layout.createSequentialGroup()
        .addGap(36, 36, 36)
        .addComponent(jLabel1)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(edtPkusuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(btnAlterar))
        .addGap(40, 40, 40)
        .addComponent(lblImagem)
        .addContainerGap(92, Short.MAX_VALUE))
    );

    barMenu.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

    meCadastro.setText("Cadastro");
    meCadastro.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

    miCadUsuario.setText("Usuário");
    miCadUsuario.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        miCadUsuarioActionPerformed(evt);
      }
    });
    meCadastro.add(miCadUsuario);

    jMenuItem2.setText("???");
    meCadastro.add(jMenuItem2);

    miSair.setText("Sair");
    miSair.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        miSairActionPerformed(evt);
      }
    });
    meCadastro.add(miSair);

    barMenu.add(meCadastro);

    meConsulta.setText("Consulta");
    meConsulta.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

    miConUsuario.setText("Usuário");
    miConUsuario.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        miConUsuarioActionPerformed(evt);
      }
    });
    meConsulta.add(miConUsuario);

    jMenuItem3.setText("???");
    jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        jMenuItem3ActionPerformed(evt);
      }
    });
    meConsulta.add(jMenuItem3);

    barMenu.add(meConsulta);

    meSobre.setText("Sobre");
    meSobre.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
    barMenu.add(meSobre);

    setJMenuBar(barMenu);

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
    );

    pack();
  }// </editor-fold>//GEN-END:initComponents

  private void miConUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miConUsuarioActionPerformed
    //crio uma tela de cadastro de usuário
    FrConUsuario telaConsulta = new FrConUsuario(this, rootPaneCheckingEnabled);
    
    //Torno a tela visível
    telaConsulta.setVisible(true);
  }//GEN-LAST:event_miConUsuarioActionPerformed

  private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
    // TODO add your handling code here:
  }//GEN-LAST:event_jMenuItem3ActionPerformed

  private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
    URL caminhoImagem = getClass().getResource("/images/logo_mini.png");

    ImageIcon icon = new ImageIcon(caminhoImagem);

    // Define o ícone da janela
    this.setIconImage(icon.getImage());
  }//GEN-LAST:event_formWindowOpened

  private void miSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miSairActionPerformed
    this.dispose();
  }//GEN-LAST:event_miSairActionPerformed

  private void miCadUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miCadUsuarioActionPerformed
    //crio uma tela de cadastro de usuário
    FrCadUsuario telaCadastro = new FrCadUsuario(this, rootPaneCheckingEnabled);
    
    //Torno a tela visível
    telaCadastro.setVisible(true);
  }//GEN-LAST:event_miCadUsuarioActionPerformed

  private void edtPkusuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edtPkusuarioActionPerformed
    // TODO add your handling code here:
  }//GEN-LAST:event_edtPkusuarioActionPerformed

  private void btnAlterarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAlterarMouseClicked
    //converter o texto do campo de pkusario para int
    int pkusuario = Integer.parseInt(edtPkusuario.getText());
    
    //contruo a tela de alteração passando o pk do usuário ao final
    FrAltUsuario telaAlteracao = new FrAltUsuario(this, rootPaneCheckingEnabled, pkusuario);
    
    telaAlteracao.setVisible(true);
  }//GEN-LAST:event_btnAlterarMouseClicked

  /**
   * @param args the command line arguments
   */
  public static void main(String args[]) {
    /* Set the Nimbus look and feel */
    //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
    /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
     */
    try {
      for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
        if ("Nimbus".equals(info.getName())) {
          javax.swing.UIManager.setLookAndFeel(info.getClassName());
          break;
        }
      }
    } catch (ClassNotFoundException ex) {
      java.util.logging.Logger.getLogger(FrMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (InstantiationException ex) {
      java.util.logging.Logger.getLogger(FrMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (IllegalAccessException ex) {
      java.util.logging.Logger.getLogger(FrMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (javax.swing.UnsupportedLookAndFeelException ex) {
      java.util.logging.Logger.getLogger(FrMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    }
    //</editor-fold>

    /* Create and display the form */
    java.awt.EventQueue.invokeLater(new Runnable() {
      public void run() {
        new FrMenu().setVisible(true);
      }
    });
  }

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JMenuBar barMenu;
  private javax.swing.JButton btnAlterar;
  private javax.swing.JTextField edtPkusuario;
  private javax.swing.JLabel jLabel1;
  private javax.swing.JMenuItem jMenuItem2;
  private javax.swing.JMenuItem jMenuItem3;
  private javax.swing.JPanel jPanel1;
  private javax.swing.JLabel lblImagem;
  private javax.swing.JMenu meCadastro;
  private javax.swing.JMenu meConsulta;
  private javax.swing.JMenu meSobre;
  private javax.swing.JMenuItem miCadUsuario;
  private javax.swing.JMenuItem miConUsuario;
  private javax.swing.JMenuItem miSair;
  // End of variables declaration//GEN-END:variables
}
